### ISSUE TITLE
Pass channel info to notify

### ISSUE THREAD

**Issue by emacsomancer** [leathekd/ercn#5]
How does one pass the channel info to notify? (For instance, I'll get a notification that someone mentioned my name, but I won't know which of the 20 channels it's from.)

**Comment by leathekd** [comment]
Good question - the channel is actually the current buffer.  Here's a bit of my notifier:

``` elisp
(defun do-notify (nickname message)
  (let* ((channel (buffer-name))
         (nick (erc-hl-nicks-trim-irc-nick nickname))
         (title (if (string-match-p (concat "^" nickname) channel)
                    nick
                  (concat nick " (" channel ")")))
         (msg (s-trim (s-collapse-whitespace message))))
    ;; call the system notifier here
    ))
```

I'll add some docs for it.

**Comment by leathekd** [comment]
I added a bit to the docs.  Feel free to reopen or open a new ticket if you need.  Thanks!

**Comment by emacsomancer** [comment]
Thanks! I'll have a look.

**Comment by emacsomancer** [comment]
So, using the new example code doesn't seem to end up pushing any notifications to me. I installed `erc-hl-nicks` too just in case that was the reason.

I have:

```
(setq ercn-notify-rules
      '((current-nick . all)
        (keyword . all)
        (pal . ("#emacs"))
        (query-buffer . all)))

;; get channel info etc.
(defun do-notify (nickname message)
  (let* ((channel (buffer-name))
         ;; using https://github.com/leathekd/erc-hl-nicks
         (nick (erc-hl-nicks-trim-irc-nick nickname))
         (title (if (string-match-p (concat "^" nickname) channel)
                    nick
                  (concat nick " (" channel ")")))
     (shell-command (concat "notify-send -u critical -t 1800000  " " '" nickname "' '" message "'")))   
     ;; Using https://github.com/magnars/s.el
   ;      (msg (s-trim (s-collapse-whitespace message))))
    ;; call the system notifier here
    ))

;; OLD one
;; (defun do-notify (nickname message)
;;   ;; notification code goes here
;;  (shell-command (concat "notify-send -u critical -t 1800000  " " '" nickname "' '" message "'"))
;;   )

(add-hook 'ercn-notify-hook 'do-notify)
```

With "OLD one", I got notifications, with the new do-notify function, I don't get anything. Can you point me in the right direction?

**Comment by leathekd** [comment]
Looks like your call to `shell-command` is actually inside the binding block of the `let*`.  Should be fine if you move it down inside the body.

That is, from this:

``` elisp
(let* ((foo "bar")
       ;; oops
       (message foo))
  )
```

To this:

``` elisp
(let* ((foo "bar"))  
  (message foo))
```

**Comment by emacsomancer** [comment]
Hmm...now I get notifications again, but still without channel-info:

```
;; get channel info etc.
(defun do-notify (nickname message)
  (let* ((channel (buffer-name))
         ;; using https://github.com/leathekd/erc-hl-nicks
         (nick (erc-hl-nicks-trim-irc-nick nickname))
         (title (if (string-match-p (concat "^" nickname) channel)
                    nick
                  (concat nick " (" channel ")"))))
     (shell-command (concat "notify-send -u critical -t 1800000  " " '" nick "' '" message "'"))
     ;; Using https://github.com/magnars/s.el
   ;      (msg (s-trim (s-collapse-whitespace message))))
    ;; call the system notifier here
    ))
```

What am I missing?

**Comment by leathekd** [comment]
You aren't putting the channel info into the notification.  :)  You probably want to replace `nick` in your call to `shell-command` with `title`.

**Comment by dakrone** [comment]
Also, rather than running a shell-command with `nick` and `message` in it that could potentially be escaped and cause shell execs, I'd recommend checking out https://github.com/jwiegley/alert (which can use notify-send)

**Comment by emacsomancer** [comment]
Got it working.

Wiegley's alert is very nice.
